<?php

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_insert().
 */
function acquia_perz_entity_insert(EntityInterface $entity) {
  \Drupal::getContainer()
    ->get('acquia_perz.export_content')
    ->exportEntity($entity);
}

/**
 * Implements hook_entity_update().
 */
function acquia_perz_entity_update(EntityInterface $entity) {
  \Drupal::getContainer()
    ->get('acquia_perz.export_content')
    ->exportEntity($entity);
}

/**
 * Implements hook_entity_delete().
 */
function acquia_perz_entity_delete(EntityInterface $entity) {
  \Drupal::getContainer()
    ->get('acquia_perz.export_content')
    ->deleteEntity($entity);
}

/**
 * Implements hook_entity_translation_delete().
 */
function acquia_perz_entity_translation_delete(EntityInterface $translation) {
  \Drupal::getContainer()
    ->get('acquia_perz.export_content')
    ->deleteTranslation($translation);
}
