<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 * Implements hook_page_attachments() to insert JavaScript to the appropriate scope/region of the page.
 */
function acquia_lift_page_attachments(array &$page) {
  $page_attachments_manager = \Drupal::service('acquia_lift.service.page.page_attachments_manager');
  if (!$page_attachments_manager->shouldAttach()) {
    return;
  }

  $page['#attached']['drupalSettings']['acquia_lift'] = $page_attachments_manager->getDrupalSettings();
  $page['#attached']['library'][] = $page_attachments_manager->getLibrary();
}

/**
 * Implements hook_ENTITY_TYPE_view_alter() for node entities.
 */
function acquia_lift_node_view_alter(array &$build, EntityInterface $node, EntityViewDisplayInterface $display) {
  // When viewing a node, create populate its page context.
  if ($display->getOriginalMode() !== 'full') {
    return;
  }

  \Drupal::service('acquia_lift.service.page.page_context')->set($node);
}