acquia_perz.settings:
  type: config_object
  label: 'Acquia Perz CIS Settings'
  mapping:
    cis:
      type: mapping
      mapping:
        api_key:
          type: string
          label: 'API Key'
        account_id:
          type: string
          label: 'Account id'
        endpoint:
          type: string
          label: 'Endpoint'
        origin:
          type: string
          label: 'Origin'
        environment:
          type: string
          label: 'Environment'
        discovery_enpoint_page_size:
          type: integer
          label: 'Discovery enpoint page size'
