<?php

/**
 * @file
 * Drupal Module: Acquia Lift - Publisher.
 *
 * Acquia Content Hub Publisher exports content from your Drupal site to
 * Content Hub services. This module alters the behavior of the default
 * functionality.
 */

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_insert().
 */
function acquia_lift_publisher_entity_insert(EntityInterface $entity) {
  _acquia_lift_publisher_trigger_queue($entity);
}

/**
 * Implements hook_entity_update().
 */
function acquia_lift_publisher_entity_update(EntityInterface $entity) {
  _acquia_lift_publisher_trigger_queue($entity);
}

/**
 * Triggers the Content Hub export process.
 *
 * @param \Drupal\Core\Entity\EntityInterface $entity
 *   The current entity.
 */
function _acquia_lift_publisher_trigger_queue(EntityInterface $entity): void {
  \Drupal::getContainer()
    ->get('acquia_lift_publisher.publishing_actions')
    ->triggerQueue($entity);
}
