<?php

/**
 * @file
 * Drupal Module: Acquia Lift - Publisher.
 *
 * Acquia Content Hub Publisher exports content from your Drupal site to
 * Content Hub services. This module alters the behavior of the default
 * functionality.
 */

use Drupal\acquia_lift_publisher\Form\AcquiaLiftPublisherSettingsForm;
use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_insert().
 */
function acquia_lift_publisher_entity_insert(EntityInterface $entity) {
  _acquia_lift_publisher_trigger_queue($entity);
}

/**
 * Implements hook_entity_update().
 */
function acquia_lift_publisher_entity_update(EntityInterface $entity) {
  _acquia_lift_publisher_trigger_queue($entity);
}

/**
 * Triggers the Content Hub export process.
 *
 * @param \Drupal\Core\Entity\EntityInterface $entity
 *   The current entity.
 */
function _acquia_lift_publisher_trigger_queue(EntityInterface $entity): void {
  // Skip unnecessary actions if the entity is not a content entity.
  if (!$entity instanceof ContentEntityInterface) {
    return;
  }

  $container = \Drupal::getContainer();
  $publish_config = $container->get('acquia_lift_publisher.settings');
  $export_queue = $container->get('acquia_contenthub_publisher.acquia_contenthub_export_queue');
  if (!$publish_config->get(AcquiaLiftPublisherSettingsForm::$pushSettingField) ||
    $export_queue->getQueueCount() < 0) {
    return;
  }

  $export_queue->processQueueItems();
}
